import { useRef, useEffect, useCallback } from 'react';
import type { Point } from '../types/ecg';

interface ECGAnimationHookProps {
  pathPoints: Point[]; // The full waveform points generated by useECGWaveformData
}

/**
 * Custom hook to manage the SVG animation of the ECG waveform.
 * It handles the drawing, pointer movement, and erase-and-draw mechanism.
 */
export const useECGAnimation = ({ pathPoints }: ECGAnimationHookProps) => {
  const svgRef = useRef<SVGSVGElement>(null); // Reference to the main SVG element
  const animationRef = useRef<number>(0); // Request animation frame ID
  const lastTimestampRef = useRef<number>(0); // Timestamp of the last animation frame
  const pointerXRef = useRef<number>(0); // Current X position of the pointer
  const firstSweepRef = useRef<boolean>(true); // Flag for the initial sweep
  // Points currently drawn on the SVG path (can include null for erased sections)
  const drawnPointsRef = useRef<(Point | null)[]>([]);

  // SVG elements references
  const waveformPathRef = useRef<SVGPathElement | null>(null);
  const pointerHeadRef = useRef<SVGCircleElement | null>(null);
  const gridGroupRef = useRef<SVGGElement | null>(null);

  // Constants for SVG dimensions and animation
  const PIXELS_PER_SECOND = 150;
  const POINTER_RADIUS = 6;
  const ERASE_WIDTH = 12; // Width of the "erasing" segment behind the pointer
  const SVG_WIDTH = 1000;
  const SVG_HEIGHT = 400;

  /**
   * Converts an array of points to an SVG path data string.
   * Handles null points for erased sections, creating multiple path segments.
   * @param pts Array of points (or null) to convert.
   * @returns SVG path data string.
   */
  const pointsToPath = useCallback((pts: (Point | null)[]): string => {
    return pts.reduce((str, p, i) => {
      if (!p) return str; // Skip null points
      // If it's the first point or the previous point was null, start a new path segment ('M')
      // Otherwise, continue the current segment ('L')
      return str + (i === 0 || !pts[i - 1] ? 'M' : ' L') + ` ${p.x} ${p.y}`;
    }, '');
  }, []);

  /**
   * Draws the grid lines on the SVG canvas.
   * Creates both vertical and horizontal lines for a standard ECG grid appearance.
   */
  const drawGrid = useCallback(() => {
    if (!svgRef.current) return;

    // Clear existing grid if it already exists, or create a new group
    if (gridGroupRef.current) {
      gridGroupRef.current.innerHTML = '';
    } else {
      gridGroupRef.current = document.createElementNS('http://www.w3.org/2000/svg', 'g');
      gridGroupRef.current.setAttribute('class', 'ecg-grid'); // Add a class for potential styling
      svgRef.current.appendChild(gridGroupRef.current);
    }

    const smallGridSize = 8; // Size for small grid squares
    const majorGridSize = 40; // Size for major grid squares (5 small squares)

    // Vertical lines
    for (let x = 0; x <= SVG_WIDTH; x += smallGridSize) {
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      line.setAttribute('x1', x.toString());
      line.setAttribute('y1', '0');
      line.setAttribute('x2', x.toString());
      line.setAttribute('y2', SVG_HEIGHT.toString());
      // Make major grid lines thicker/darker
      line.setAttribute('stroke', (x % majorGridSize === 0) ? '#ddd' : '#eee');
      line.setAttribute('stroke-width', (x % majorGridSize === 0) ? '0.7' : '0.4');
      gridGroupRef.current!.appendChild(line);
    }
    // Horizontal lines
    for (let y = 0; y <= SVG_HEIGHT; y += smallGridSize) {
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      line.setAttribute('x1', '0');
      line.setAttribute('y1', y.toString());
      line.setAttribute('x2', SVG_WIDTH.toString());
      line.setAttribute('y2', y.toString());
      // Make major grid lines thicker/darker
      line.setAttribute('stroke', (y % majorGridSize === 0) ? '#ddd' : '#eee');
      line.setAttribute('stroke-width', (y % majorGridSize === 0) ? '0.7' : '0.4');
      gridGroupRef.current!.appendChild(line);
    }
  }, []);

  /**
   * Initializes the SVG elements (path and pointer) and draws the grid.
   * This is called once on component mount or when a full reset is needed.
   */
  const initializeSVG = useCallback(() => {
    if (!svgRef.current) return;

    drawGrid(); // Draw the grid background

    // Remove existing waveform path and pointer if they exist to prevent duplicates
    if (waveformPathRef.current) {
      svgRef.current.removeChild(waveformPathRef.current);
    }
    if (pointerHeadRef.current) {
      svgRef.current.removeChild(pointerHeadRef.current);
    }

    // Create and append the waveform path element
    waveformPathRef.current = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    waveformPathRef.current.setAttribute('stroke', '#007bff'); // ECG line color
    waveformPathRef.current.setAttribute('fill', 'none');
    waveformPathRef.current.setAttribute('stroke-width', '2');
    svgRef.current.appendChild(waveformPathRef.current);

    // Create and append the pointer (circle) element
    pointerHeadRef.current = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    pointerHeadRef.current.setAttribute('r', POINTER_RADIUS.toString());
    pointerHeadRef.current.setAttribute('fill', '#007bff'); // Pointer fill color
    pointerHeadRef.current.setAttribute('stroke', '#fff'); // Pointer border color
    pointerHeadRef.current.setAttribute('stroke-width', '2');
    svgRef.current.appendChild(pointerHeadRef.current);
  }, [drawGrid]);

  /**
   * The main animation loop for the ECG waveform.
   * It updates the pointer position, draws new points, and "erases" old points.
   * @param timestamp High-resolution time value provided by requestAnimationFrame.
   */
  const animationLoop = useCallback((timestamp: number) => {
    // Calculate time difference since last frame in seconds
    const dt = lastTimestampRef.current ? (timestamp - lastTimestampRef.current) / 1000 : 0;
    lastTimestampRef.current = timestamp;

    // Update pointer's X position based on PIXELS_PER_SECOND speed
    pointerXRef.current += PIXELS_PER_SECOND * dt;

    // Find the index of the point in pathPoints that corresponds to the current pointerX
    let idx = pathPoints.findIndex(pt => pt.x >= pointerXRef.current);
    if (idx < 0) idx = pathPoints.length - 1; // If pointer passed all points, take the last one

    if (firstSweepRef.current) {
      // During the first sweep, progressively draw the waveform from left to right
      drawnPointsRef.current = pathPoints.slice(0, idx + 1);
      if (waveformPathRef.current) {
        waveformPathRef.current.setAttribute('d', pointsToPath(drawnPointsRef.current));
      }
      // Once the pointer reaches the end of the SVG, switch to the continuous erase-and-draw mode
      if (pointerXRef.current > SVG_WIDTH) {
        firstSweepRef.current = false;
        // Reinitialize drawnPointsRef to a full copy of pathPoints,
        // as subsequent updates will modify points in place or replace with null
        drawnPointsRef.current = [...pathPoints];
      }
    } else {
      // Continuous erase-and-draw mode
      if (pointerXRef.current > SVG_WIDTH) {
        // If pointer goes past SVG width, reset it to the beginning
        pointerXRef.current = 0;
        // Re-generate waveform points to ensure seamless loop and new patterns
        // Note: `pathPoints` prop itself needs to be updated by parent if data changes
        // For dynamic data, the parent component needs to call a function that updates pathPoints
        // This hook reacts to changes in `pathPoints` prop.
      }

      // Define the "erasure" zone around the pointer
      const eraseStart = pointerXRef.current - ERASE_WIDTH / 2;
      const eraseEnd = pointerXRef.current + ERASE_WIDTH / 2;

      // Find the range of points that need to be "erased" (set to null) or "drawn" (set back to actual point)
      const startIndexToErase = drawnPointsRef.current.findIndex(pt => pt && pt.x >= eraseStart);
      const endIndexToErase = drawnPointsRef.current.findIndex(pt => pt && pt.x > eraseEnd);

      // Erase points in the specified range by setting them to null
      for (let i = (startIndexToErase < 0 ? 0 : startIndexToErase); i < (endIndexToErase < 0 ? drawnPointsRef.current.length : endIndexToErase); i++) {
        if (drawnPointsRef.current[i] && drawnPointsRef.current[i]!.x >= eraseStart && drawnPointsRef.current[i]!.x <= eraseEnd) {
             drawnPointsRef.current[i] = null; // Set points within the erase window to null
        } else {
            // Restore points that are now outside the erase window, but not yet drawn by the pointer head
            // This is a subtle point: points that *just* passed the erase window should be null
            // until the pointer head reaches them and re-draws them from the `pathPoints`.
            // The logic below for `drawingPoints` handles restoring them.
        }
      }

      // Draw the new points that the pointer has reached
      for (let i = 0; i < pathPoints.length; i++) {
        const point = pathPoints[i];
        if (point && point.x <= pointerXRef.current + POINTER_RADIUS) { // Draw points up to pointer head
          drawnPointsRef.current[i] = point;
        }
      }

      // Update the SVG path with the current drawn points
      if (waveformPathRef.current) {
        waveformPathRef.current.setAttribute('d', pointsToPath(drawnPointsRef.current));
      }
    }

    // Update the position of the pointer head circle
    const currentPointUnderPointer = pathPoints[idx];
    if (currentPointUnderPointer && pointerHeadRef.current) {
      pointerHeadRef.current.setAttribute('cx', currentPointUnderPointer.x.toString());
      pointerHeadRef.current.setAttribute('cy', currentPointUnderPointer.y.toString());
    }

    // Request the next animation frame
    animationRef.current = requestAnimationFrame(animationLoop);
  }, [pathPoints, pointsToPath]); // Depend on pathPoints so changes trigger re-animation

  // Effect to initialize SVG and start animation on mount
  useEffect(() => {
    initializeSVG();
    // Initialize drawnPointsRef with nulls to start, will be filled during first sweep
    drawnPointsRef.current = Array(pathPoints.length).fill(null);
    animationRef.current = requestAnimationFrame(animationLoop);

    // Cleanup function: cancel animation frame when component unmounts
    return () => {
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
    };
  }, [initializeSVG, animationLoop, pathPoints]); // Re-run if pathPoints changes (e.g., "Apply Changes")

  return { svgRef }; // Return the ref to be attached to the SVG element
};
